CREATE DATABASE BTTHUCHANH01_SESSION02;
USE BTTHUCHANH01_SESSION02;

CREATE TABLE Persons (
	personId INT NOT NULL PRIMARY KEY,
    lastName VARCHAR(255) NOT NULL,
    firstName VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE,
    address VARCHAR(255),
    city VARCHAR(255)
);

CREATE TABLE HOBBIES (
	id INT PRIMARY KEY,
    name VARCHAR(100) CHECK(LENGTH(name) > 4),
    personId INT ,
    FOREIGN KEY (personId) REFERENCES Persons(personId)
);

ALTER TABLE Persons
ADD COLUMN phone VARCHAR(15),
DROP COLUMN city;
